language: go

dist: xenial
os: linux

sudo: required

go:
  - 1.13.x
go_import_path: github.com/nuodb/nuodb-golang-operator

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - NUODB_OP_IMAGE=$DOCKER_SERVER/$REPO_NAME:v$TRAVIS_BUILD_NUMBER
    - HOME_DIR=$TRAVIS_BUILD_DIR
    - GO111MODULE=on

before_install:
  - |
    set -e
    # fail loudly when force-pushed
    MODIFIED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)
    # waiting for native solution https://github.com/travis-ci/travis-ci/issues/6301
    if [ -z "${MODIFIED_FILES}" ]; then
      # $TRAVIS_COMMIT_RANGE will be empty for builds triggered by the initial commit of a new branch.
      echo "No changes found, can not determine what to skip"
    elif ! echo ${MODIFIED_FILES} | grep -qvE '(\.md$)'; then
      echo "Only docs were updated, stopping build process."
      exit
    fi

install:
  - chmod +x scripts/ci/install-deps.sh
  - chmod +x scripts/ci/build_operator.sh
  - chmod +x scripts/ci/test_operator.sh
  - scripts/ci/install-deps.sh

script:
  - go test -v ./pkg/...
  - scripts/ci/build_operator.sh
  - scripts/ci/test_operator.sh
