apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nuodbs.nuodb.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.smHealth
    name: SM
    type: string
  - JSONPath: .status.teHealth
    name: TE
    type: string
  - JSONPath: .status.databaseHealth
    name: Database
    type: string
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .status.controllerVersion
    name: ControllerVersion
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: nuodb.com
  names:
    categories:
    - nuodb
    kind: Nuodb
    listKind: NuodbList
    plural: nuodbs
    shortNames:
    - nuodb
    singular: nuodb
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            container:
              description: 'container NuoDB fully qualified image name (FQIN) for
                the Docker image to use container: "registry.connect.redhat.com/nuodb/nuodb-ce:latest"
                Example: container: nuodb/nuodb-ce:latest'
              type: string
            dbAvailability:
              description: 'dbAvailability  Availability requirement for this database.  Values
                are:  single-instance - The operator manages a single instance of
                each NuoDB                   component (Admin, SM, TE).  In the event
                that one                   component goes down or becomes unavailable,
                the                   operator will automatically replace the failed
                component.                   This is the most resource friendly option
                for applications                   that can tolerate a brief outage.  multiple-instance
                - The operator manages multiple instances of each                     NuoDB
                component (Admin, SM, TE).  high-availability - The operator will
                maximize performance and reliability.  manual - The operator will
                enforce custom provided Admin, SM, TE instance counts.  The default
                is: "high-availability"'
              type: string
            dbName:
              description: 'dbName NuoDB Database name.  must consist of lowercase
                alphanumeric characters ''[a-z0-9]+'' example: dbName: test'
              type: string
            dbPassword:
              description: 'dbPassword Database password Example: dbPassword: secret'
              type: string
            dbUser:
              description: 'dbUser Name of Database user example: dbUser: dba'
              type: string
            engineOptions:
              description: 'engineOptions Additional "nuodb" engine options Format:
                <option> <value> <option> <value> ... Example: engineOptions: ""'
              type: string
            smCount:
              description: 'smCount Number of SM service pods. Requires 1 SM available
                for each NuoDB Database example: smCount: 1'
              format: int32
              type: integer
            smCpu:
              description: 'smCpu SM CPU cores to request example: smCpu: 1'
              type: string
            smMemory:
              description: 'smMemory SM memory example: smMemory: 2Gi'
              type: string
            smStorageClass:
              description: 'smStorageClass SM persistent storage class name Example:
                smStorageClass: local-disk'
              type: string
            smStorageSize:
              description: 'smStorageSize Storage manager (SM) volume size Example:
                smStorageSize: 20Gi'
              type: string
            storageMode:
              description: 'storageMode Run NuoDB using a persistent, local, disk
                volume "persistent" or volatile storage "ephemeral".  Must be set
                to one of those values. example: storageMode: persistent'
              type: string
            teCount:
              description: 'teCount Number of transaction engines (TE) nodes. Limit
                is 3 in CE version of NuoDB Example: teCount: 1'
              format: int32
              type: integer
            teCpu:
              description: 'teCpu TE CPU cores to request Example: teCpu: 1'
              type: string
            teMemory:
              description: 'teMemory TE memory Example: teMemory: 2Gi'
              type: string
          required:
          - container
          - dbAvailability
          - dbName
          - dbPassword
          - dbUser
          - engineOptions
          - smCount
          - smCpu
          - smMemory
          - smStorageClass
          - smStorageSize
          - storageMode
          - teCount
          - teCpu
          - teMemory
          type: object
        status:
          properties:
            controllerVersion:
              description: ControllerVersion is the version of the controller that
                last updated the NuoDB Domain
              type: string
            databaseHealth:
              description: Health of the NuoDB Database
              type: string
            phase:
              description: Orchestration phase of the NuoDB Database
              type: string
            smHealth:
              description: AdminHealth of the NuoDB Database
              type: string
            smReadyCount:
              description: SM Node Ready Count
              format: int32
              type: integer
            teHealth:
              description: TE Health of the NuoDB Database
              type: string
            teReadyCount:
              description: TE Node Ready Count
              format: int32
              type: integer
          type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
